import { ColState } from "./datatypes";

export const headerConfig = [
    { label: "Complaint", id: 'complaint_id' },
    { label: "Submitted", id: 'submitted_via' },
    { label: "Date", id: 'date_submitted' },
    { label: "Recevied", id: 'date_received' },
    { label: "State", id: 'label' },
    { label: "Product", id: 'product' },
    { label: "Sub", id: 'sub_product' },
    { label: "Issue", id: 'issue' },
    { label: "Response", id: 'company_response_to_consumer' }

];

export const jsonData: ColState[] = [
    {
        "Complaint": 4848023,
        "Submitted": "Referral",
        "Date": 44493,
        "Recevied": 44496,
        "State": "NY",
        "Product": "Mortgage",
        "Sub": "Conventional home mortgage",
        "Issue": "Applying for a mortgage or refinancing an existing mortgage",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3621464,
        "Submitted": "Web",
        "Date": 43945,
        "Recevied": 43945,
        "State": "FL",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub": "Refund anticipation check",
        "Issue": "Lost or stolen check",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5818349,
        "Submitted": "Web",
        "Date": 44769,
        "Recevied": 44769,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5820224,
        "Submitted": "Referral",
        "Date": 44769,
        "Recevied": 44770,
        "State": "VA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Closing your account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6237961,
        "Submitted": "Web",
        "Date": 44888,
        "Recevied": 44888,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 4348292,
        "Submitted": "Web",
        "Date": 44320,
        "Recevied": 44320,
        "State": "TX",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Closing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 4090544,
        "Submitted": "Web",
        "Date": 44220,
        "Recevied": 44220,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5337082,
        "Submitted": "Web",
        "Date": 44638,
        "Recevied": 44638,
        "State": "TX",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6203657,
        "Submitted": "Web",
        "Date": 44879,
        "Recevied": 44879,
        "State": "VA",
        "Product": "Checking or savings account",
        "Sub": "Other banking product or service",
        "Issue": "Closing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5092497,
        "Submitted": "Web",
        "Date": 44571,
        "Recevied": 44571,
        "State": "FL",
        "Product": "Mortgage",
        "Sub": "Conventional home mortgage",
        "Issue": "Applying for a mortgage or refinancing an existing mortgage",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5336959,
        "Submitted": "Web",
        "Date": 44638,
        "Recevied": 44638,
        "State": "KS",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Opening an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5618881,
        "Submitted": "Web",
        "Date": 44709,
        "Recevied": 44709,
        "State": "GA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 2850455,
        "Submitted": "Web",
        "Date": 43180,
        "Recevied": 43180,
        "State": "FL",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub": "International money transfer",
        "Issue": "Fraud or scam",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5618923,
        "Submitted": "Web",
        "Date": 44709,
        "Recevied": 44709,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 7230934,
        "Submitted": "Web",
        "Date": 45117,
        "Recevied": 45117,
        "State": "FL",
        "Product": "Mortgage",
        "Sub": "Conventional home mortgage",
        "Issue": "Applying for a mortgage or refinancing an existing mortgage",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 2721761,
        "Submitted": "Web",
        "Date": 43046,
        "Recevied": 43046,
        "State": "CT",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Advertising and marketing, including promotional offers",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 2784223,
        "Submitted": "Web",
        "Date": 43116,
        "Recevied": 43116,
        "State": "OH",
        "Product": "Vehicle loan or lease",
        "Sub": "Loan",
        "Issue": "Getting a loan or lease",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3119597,
        "Submitted": "Referral",
        "Date": 43473,
        "Recevied": 43473,
        "State": "NJ",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5819430,
        "Submitted": "Web",
        "Date": 44770,
        "Recevied": 44770,
        "State": "FL",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 7028167,
        "Submitted": "Web",
        "Date": 45071,
        "Recevied": 45071,
        "State": "TX",
        "Product": "Debt collection",
        "Sub": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5683986,
        "Submitted": "Web",
        "Date": 44730,
        "Recevied": 44730,
        "State": "IL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3820525,
        "Submitted": "Web",
        "Date": 44072,
        "Recevied": 44072,
        "State": "IL",
        "Product": "Debt collection",
        "Sub": "Credit card debt",
        "Issue": "Attempts to collect debt not owed",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6963797,
        "Submitted": "Web",
        "Date": 45058,
        "Recevied": 45058,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5333369,
        "Submitted": "Phone",
        "Date": 44637,
        "Recevied": 44638,
        "State": "MI",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Opening an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3820697,
        "Submitted": "Web",
        "Date": 44072,
        "Recevied": 44072,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5335281,
        "Submitted": "Web",
        "Date": 44637,
        "Recevied": 44637,
        "State": "NC",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5820848,
        "Submitted": "Web",
        "Date": 44770,
        "Recevied": 44770,
        "State": "TX",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 7267115,
        "Submitted": "Web",
        "Date": 45125,
        "Recevied": 45125,
        "State": "CA",
        "Product": "Payday loan, title loan, or personal loan",
        "Sub": "Personal line of credit",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 5332726,
        "Submitted": "Web",
        "Date": 44636,
        "Recevied": 44636,
        "State": "PA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Opening an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6023115,
        "Submitted": "Web",
        "Date": 44831,
        "Recevied": 44831,
        "State": "VA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6120829,
        "Submitted": "Web",
        "Date": 44858,
        "Recevied": 44858,
        "State": "WA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6452545,
        "Submitted": "Web",
        "Date": 44945,
        "Recevied": 44945,
        "State": "VA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5046164,
        "Submitted": "Web",
        "Date": 44558,
        "Recevied": 44558,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 3845288,
        "Submitted": "Web",
        "Date": 44085,
        "Recevied": 44085,
        "State": "IN",
        "Product": "Mortgage",
        "Sub": "Conventional home mortgage",
        "Issue": "Trouble during payment process",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 3087443,
        "Submitted": "Referral",
        "Date": 43433,
        "Recevied": 43433,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 5734515,
        "Submitted": "Web",
        "Date": 44747,
        "Recevied": 44747,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6797771,
        "Submitted": "Phone",
        "Date": 45021,
        "Recevied": 45027,
        "State": "MI",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5736591,
        "Submitted": "Web",
        "Date": 44747,
        "Recevied": 44747,
        "State": "NY",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub": "International money transfer",
        "Issue": "Fraud or scam",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3093232,
        "Submitted": "Web",
        "Date": 43440,
        "Recevied": 43445,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6100753,
        "Submitted": "Web",
        "Date": 44852,
        "Recevied": 44852,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5736847,
        "Submitted": "Web",
        "Date": 44747,
        "Recevied": 44747,
        "State": "MA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 3093295,
        "Submitted": "Web",
        "Date": 43440,
        "Recevied": 43440,
        "State": "MI",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Closing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3841170,
        "Submitted": "Web",
        "Date": 44085,
        "Recevied": 44085,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6060828,
        "Submitted": "Web",
        "Date": 44841,
        "Recevied": 44841,
        "State": "TX",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 6189194,
        "Submitted": "Web",
        "Date": 44875,
        "Recevied": 44875,
        "State": "MD",
        "Product": "Debt collection",
        "Sub": "Mortgage debt",
        "Issue": "False statements or representation",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6186689,
        "Submitted": "Web",
        "Date": 44875,
        "Recevied": 44875,
        "State": "GA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 5030560,
        "Submitted": "Phone",
        "Date": 44551,
        "Recevied": 44551,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 2554204,
        "Submitted": "Postal mail",
        "Date": 42906,
        "Recevied": 42907,
        "State": "NV",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6896720,
        "Submitted": "Web",
        "Date": 45043,
        "Recevied": 45043,
        "State": "TN",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 2553578,
        "Submitted": "Web",
        "Date": 42906,
        "Recevied": 42906,
        "State": "AZ",
        "Product": "Checking or savings account",
        "Sub": "Other banking product or service",
        "Issue": "Closing an account",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 3593281,
        "Submitted": "Web",
        "Date": 43925,
        "Recevied": 43925,
        "State": "PA",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub": "Mobile or digital wallet",
        "Issue": "Fraud or scam",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6237907,
        "Submitted": "Web",
        "Date": 44888,
        "Recevied": 44888,
        "State": "MO",
        "Product": "Debt collection",
        "Sub": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6194261,
        "Submitted": "Web",
        "Date": 44877,
        "Recevied": 44877,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5951477,
        "Submitted": "Web",
        "Date": 44809,
        "Recevied": 44809,
        "State": "GA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6082462,
        "Submitted": "Web",
        "Date": 44847,
        "Recevied": 44847,
        "State": "TN",
        "Product": "Checking or savings account",
        "Sub": "Savings account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6100824,
        "Submitted": "Web",
        "Date": 44852,
        "Recevied": 44852,
        "State": "TN",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Opening an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5235763,
        "Submitted": "Referral",
        "Date": 44607,
        "Recevied": 44609,
        "State": "MI",
        "Product": "Mortgage",
        "Sub": "Home equity loan or line of credit (HELOC)",
        "Issue": "Trouble during payment process",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 6189124,
        "Submitted": "Web",
        "Date": 44875,
        "Recevied": 44875,
        "State": "PA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Closing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 2991112,
        "Submitted": "Web",
        "Date": 43326,
        "Recevied": 43328,
        "State": "DC",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6862692,
        "Submitted": "Web",
        "Date": 45035,
        "Recevied": 45035,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3093135,
        "Submitted": "Web",
        "Date": 43440,
        "Recevied": 43440,
        "State": "FL",
        "Product": "Mortgage",
        "Sub": "Other type of mortgage",
        "Issue": "Struggling to pay mortgage",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6188850,
        "Submitted": "Web",
        "Date": 44875,
        "Recevied": 44875,
        "State": "TX",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6239495,
        "Submitted": "Referral",
        "Date": 44887,
        "Recevied": 44888,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3592843,
        "Submitted": "Web",
        "Date": 43925,
        "Recevied": 43925,
        "State": "NY",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 3076503,
        "Submitted": "Web",
        "Date": 43420,
        "Recevied": 43424,
        "State": "TX",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5781200,
        "Submitted": "Web",
        "Date": 44760,
        "Recevied": 44760,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6127521,
        "Submitted": "Web",
        "Date": 44859,
        "Recevied": 44859,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5223129,
        "Submitted": "Web",
        "Date": 44607,
        "Recevied": 44607,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6458454,
        "Submitted": "Web",
        "Date": 44945,
        "Recevied": 44945,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5668489,
        "Submitted": "Web",
        "Date": 44726,
        "Recevied": 44726,
        "State": "MI",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6068024,
        "Submitted": "Web",
        "Date": 44845,
        "Recevied": 44845,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5724436,
        "Submitted": "Phone",
        "Date": 44742,
        "Recevied": 44742,
        "State": "MD",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6189181,
        "Submitted": "Web",
        "Date": 44876,
        "Recevied": 44876,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6064564,
        "Submitted": "Web",
        "Date": 44842,
        "Recevied": 44842,
        "State": "MO",
        "Product": "Vehicle loan or lease",
        "Sub": "Loan",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 4622571,
        "Submitted": "Web",
        "Date": 44419,
        "Recevied": 44419,
        "State": "FL",
        "Product": "Debt collection",
        "Sub": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6034441,
        "Submitted": "Web",
        "Date": 44834,
        "Recevied": 44834,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub": "Government benefit card",
        "Issue": "Problem with a purchase or transfer",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6579635,
        "Submitted": "Web",
        "Date": 44973,
        "Recevied": 44973,
        "State": "NJ",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub": "Domestic (US) money transfer",
        "Issue": "Other transaction problem",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 7208864,
        "Submitted": "Web",
        "Date": 45112,
        "Recevied": 45112,
        "State": "NY",
        "Product": "Vehicle loan or lease",
        "Sub": "Loan",
        "Issue": "Struggling to pay your loan",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6231510,
        "Submitted": "Web",
        "Date": 44888,
        "Recevied": 44888,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3669052,
        "Submitted": "Web",
        "Date": 43977,
        "Recevied": 43977,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 3297104,
        "Submitted": "Web",
        "Date": 43651,
        "Recevied": 43651,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 7209138,
        "Submitted": "Web",
        "Date": 45112,
        "Recevied": 45112,
        "State": "ID",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Other features, terms, or problems",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 4291119,
        "Submitted": "Referral",
        "Date": 44294,
        "Recevied": 44298,
        "State": "FL",
        "Product": "Mortgage",
        "Sub": "Conventional home mortgage",
        "Issue": "Trouble during payment process",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5146042,
        "Submitted": "Web",
        "Date": 44586,
        "Recevied": 44586,
        "State": "NY",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3142516,
        "Submitted": "Web",
        "Date": 43500,
        "Recevied": 43500,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5131244,
        "Submitted": "Web",
        "Date": 44581,
        "Recevied": 44581,
        "State": "NY",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6022257,
        "Submitted": "Web",
        "Date": 44832,
        "Recevied": 44832,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6026873,
        "Submitted": "Web",
        "Date": 44832,
        "Recevied": 44832,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Response": "Closed with non-monetary relief"
    },
    {
        "Complaint": 3297138,
        "Submitted": "Web",
        "Date": 43651,
        "Recevied": 43651,
        "State": "TX",
        "Product": "Mortgage",
        "Sub": "FHA mortgage",
        "Issue": "Trouble during payment process",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5676146,
        "Submitted": "Web",
        "Date": 44727,
        "Recevied": 44727,
        "State": "NY",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub": "Domestic (US) money transfer",
        "Issue": "Other transaction problem",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6964251,
        "Submitted": "Web",
        "Date": 45057,
        "Recevied": 45058,
        "State": "GA",
        "Product": "Mortgage",
        "Sub": "FHA mortgage",
        "Issue": "Trouble during payment process",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6964244,
        "Submitted": "Web",
        "Date": 45057,
        "Recevied": 45058,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub": "Government benefit card",
        "Issue": "Problem with a purchase or transfer",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 6234439,
        "Submitted": "Web",
        "Date": 44887,
        "Recevied": 44887,
        "State": "MO",
        "Product": "Debt collection",
        "Sub": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 3255620,
        "Submitted": "Web",
        "Date": 43613,
        "Recevied": 43613,
        "State": "MA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 5675175,
        "Submitted": "Phone",
        "Date": 44727,
        "Recevied": 44769,
        "State": "NY",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 5763246,
        "Submitted": "Web",
        "Date": 44755,
        "Recevied": 44769,
        "State": "NC",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Other features, terms, or problems",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 3820159,
        "Submitted": "Web",
        "Date": 44071,
        "Recevied": 44071,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub": "Government benefit card",
        "Issue": "Trouble using the card",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6965959,
        "Submitted": "Web",
        "Date": 45057,
        "Recevied": 45057,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Response": "Closed with monetary relief"
    },
    {
        "Complaint": 4185802,
        "Submitted": "Web",
        "Date": 44259,
        "Recevied": 44259,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub": "Checking account",
        "Issue": "Managing an account",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 6190474,
        "Submitted": "Web",
        "Date": 44876,
        "Recevied": 44876,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub": "Credit repair services",
        "Issue": "Confusing or missing disclosures",
        "Response": "Closed with explanation"
    },
    {
        "Complaint": 4276281,
        "Submitted": "Referral",
        "Date": 44290,
        "Recevied": 44292,
        "State": "NC",
        "Product": "Credit card or prepaid card",
        "Sub": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Response": "Closed with monetary relief"
    }
]