import { ColState } from "./datatypes";

export const headerConfig = [
    { label: "Complaint ID", id: 'complaint_id' },
    { label: "Submitted via", id: 'submitted_via' },
    { label: "Date submitted", id: 'date_submitted' },
    { label: "Date received", id: 'date_received' },
    { label: "State", id: 'label' },
    { label: "Product", id: 'product' },
    { label: "Sub-product", id: 'sub_product' },
    { label: "Issue", id: 'issue' },
    { label: "Company response to consumer", id: 'company_response_to_consumer' },
    { label: "Timely response?", id: 'timely_response' }

];

export const jsonData: ColState[] = [
    {
        "Complaint ID": 4848023,
        "Submitted via": "Referral",
        "Date submitted": 44493,
        "Date received": 44496,
        "State": "NY",
        "Product": "Mortgage",
        "Sub-product": "Conventional home mortgage",
        "Issue": "Applying for a mortgage or refinancing an existing mortgage",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3621464,
        "Submitted via": "Web",
        "Date submitted": 43945,
        "Date received": 43945,
        "State": "FL",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub-product": "Refund anticipation check",
        "Issue": "Lost or stolen check",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5818349,
        "Submitted via": "Web",
        "Date submitted": 44769,
        "Date received": 44769,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5820224,
        "Submitted via": "Referral",
        "Date submitted": 44769,
        "Date received": 44770,
        "State": "VA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Closing your account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6237961,
        "Submitted via": "Web",
        "Date submitted": 44888,
        "Date received": 44888,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 4348292,
        "Submitted via": "Web",
        "Date submitted": 44320,
        "Date received": 44320,
        "State": "TX",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Closing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 4090544,
        "Submitted via": "Web",
        "Date submitted": 44220,
        "Date received": 44220,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5337082,
        "Submitted via": "Web",
        "Date submitted": 44638,
        "Date received": 44638,
        "State": "TX",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6203657,
        "Submitted via": "Web",
        "Date submitted": 44879,
        "Date received": 44879,
        "State": "VA",
        "Product": "Checking or savings account",
        "Sub-product": "Other banking product or service",
        "Issue": "Closing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5092497,
        "Submitted via": "Web",
        "Date submitted": 44571,
        "Date received": 44571,
        "State": "FL",
        "Product": "Mortgage",
        "Sub-product": "Conventional home mortgage",
        "Issue": "Applying for a mortgage or refinancing an existing mortgage",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5336959,
        "Submitted via": "Web",
        "Date submitted": 44638,
        "Date received": 44638,
        "State": "KS",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Opening an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5618881,
        "Submitted via": "Web",
        "Date submitted": 44709,
        "Date received": 44709,
        "State": "GA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 2850455,
        "Submitted via": "Web",
        "Date submitted": 43180,
        "Date received": 43180,
        "State": "FL",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub-product": "International money transfer",
        "Issue": "Fraud or scam",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5618923,
        "Submitted via": "Web",
        "Date submitted": 44709,
        "Date received": 44709,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 7230934,
        "Submitted via": "Web",
        "Date submitted": 45117,
        "Date received": 45117,
        "State": "FL",
        "Product": "Mortgage",
        "Sub-product": "Conventional home mortgage",
        "Issue": "Applying for a mortgage or refinancing an existing mortgage",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 2721761,
        "Submitted via": "Web",
        "Date submitted": 43046,
        "Date received": 43046,
        "State": "CT",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Advertising and marketing, including promotional offers",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 2784223,
        "Submitted via": "Web",
        "Date submitted": 43116,
        "Date received": 43116,
        "State": "OH",
        "Product": "Vehicle loan or lease",
        "Sub-product": "Loan",
        "Issue": "Getting a loan or lease",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3119597,
        "Submitted via": "Referral",
        "Date submitted": 43473,
        "Date received": 43473,
        "State": "NJ",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5819430,
        "Submitted via": "Web",
        "Date submitted": 44770,
        "Date received": 44770,
        "State": "FL",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 7028167,
        "Submitted via": "Web",
        "Date submitted": 45071,
        "Date received": 45071,
        "State": "TX",
        "Product": "Debt collection",
        "Sub-product": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5683986,
        "Submitted via": "Web",
        "Date submitted": 44730,
        "Date received": 44730,
        "State": "IL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3820525,
        "Submitted via": "Web",
        "Date submitted": 44072,
        "Date received": 44072,
        "State": "IL",
        "Product": "Debt collection",
        "Sub-product": "Credit card debt",
        "Issue": "Attempts to collect debt not owed",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6963797,
        "Submitted via": "Web",
        "Date submitted": 45058,
        "Date received": 45058,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5333369,
        "Submitted via": "Phone",
        "Date submitted": 44637,
        "Date received": 44638,
        "State": "MI",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Opening an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3820697,
        "Submitted via": "Web",
        "Date submitted": 44072,
        "Date received": 44072,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5335281,
        "Submitted via": "Web",
        "Date submitted": 44637,
        "Date received": 44637,
        "State": "NC",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5820848,
        "Submitted via": "Web",
        "Date submitted": 44770,
        "Date received": 44770,
        "State": "TX",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 7267115,
        "Submitted via": "Web",
        "Date submitted": 45125,
        "Date received": 45125,
        "State": "CA",
        "Product": "Payday loan, title loan, or personal loan",
        "Sub-product": "Personal line of credit",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5332726,
        "Submitted via": "Web",
        "Date submitted": 44636,
        "Date received": 44636,
        "State": "PA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Opening an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6023115,
        "Submitted via": "Web",
        "Date submitted": 44831,
        "Date received": 44831,
        "State": "VA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6120829,
        "Submitted via": "Web",
        "Date submitted": 44858,
        "Date received": 44858,
        "State": "WA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6452545,
        "Submitted via": "Web",
        "Date submitted": 44945,
        "Date received": 44945,
        "State": "VA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5046164,
        "Submitted via": "Web",
        "Date submitted": 44558,
        "Date received": 44558,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3845288,
        "Submitted via": "Web",
        "Date submitted": 44085,
        "Date received": 44085,
        "State": "IN",
        "Product": "Mortgage",
        "Sub-product": "Conventional home mortgage",
        "Issue": "Trouble during payment process",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3087443,
        "Submitted via": "Referral",
        "Date submitted": 43433,
        "Date received": 43433,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5734515,
        "Submitted via": "Web",
        "Date submitted": 44747,
        "Date received": 44747,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6797771,
        "Submitted via": "Phone",
        "Date submitted": 45021,
        "Date received": 45027,
        "State": "MI",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5736591,
        "Submitted via": "Web",
        "Date submitted": 44747,
        "Date received": 44747,
        "State": "NY",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub-product": "International money transfer",
        "Issue": "Fraud or scam",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3093232,
        "Submitted via": "Web",
        "Date submitted": 43440,
        "Date received": 43445,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6100753,
        "Submitted via": "Web",
        "Date submitted": 44852,
        "Date received": 44852,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5736847,
        "Submitted via": "Web",
        "Date submitted": 44747,
        "Date received": 44747,
        "State": "MA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3093295,
        "Submitted via": "Web",
        "Date submitted": 43440,
        "Date received": 43440,
        "State": "MI",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Closing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3841170,
        "Submitted via": "Web",
        "Date submitted": 44085,
        "Date received": 44085,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6060828,
        "Submitted via": "Web",
        "Date submitted": 44841,
        "Date received": 44841,
        "State": "TX",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6189194,
        "Submitted via": "Web",
        "Date submitted": 44875,
        "Date received": 44875,
        "State": "MD",
        "Product": "Debt collection",
        "Sub-product": "Mortgage debt",
        "Issue": "False statements or representation",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6186689,
        "Submitted via": "Web",
        "Date submitted": 44875,
        "Date received": 44875,
        "State": "GA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5030560,
        "Submitted via": "Phone",
        "Date submitted": 44551,
        "Date received": 44551,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 2554204,
        "Submitted via": "Postal mail",
        "Date submitted": 42906,
        "Date received": 42907,
        "State": "NV",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6896720,
        "Submitted via": "Web",
        "Date submitted": 45043,
        "Date received": 45043,
        "State": "TN",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Getting a credit card",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 2553578,
        "Submitted via": "Web",
        "Date submitted": 42906,
        "Date received": 42906,
        "State": "AZ",
        "Product": "Checking or savings account",
        "Sub-product": "Other banking product or service",
        "Issue": "Closing an account",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3593281,
        "Submitted via": "Web",
        "Date submitted": 43925,
        "Date received": 43925,
        "State": "PA",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub-product": "Mobile or digital wallet",
        "Issue": "Fraud or scam",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6237907,
        "Submitted via": "Web",
        "Date submitted": 44888,
        "Date received": 44888,
        "State": "MO",
        "Product": "Debt collection",
        "Sub-product": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6194261,
        "Submitted via": "Web",
        "Date submitted": 44877,
        "Date received": 44877,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5951477,
        "Submitted via": "Web",
        "Date submitted": 44809,
        "Date received": 44809,
        "State": "GA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6082462,
        "Submitted via": "Web",
        "Date submitted": 44847,
        "Date received": 44847,
        "State": "TN",
        "Product": "Checking or savings account",
        "Sub-product": "Savings account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6100824,
        "Submitted via": "Web",
        "Date submitted": 44852,
        "Date received": 44852,
        "State": "TN",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Opening an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5235763,
        "Submitted via": "Referral",
        "Date submitted": 44607,
        "Date received": 44609,
        "State": "MI",
        "Product": "Mortgage",
        "Sub-product": "Home equity loan or line of credit (HELOC)",
        "Issue": "Trouble during payment process",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6189124,
        "Submitted via": "Web",
        "Date submitted": 44875,
        "Date received": 44875,
        "State": "PA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Closing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "No"
    },
    {
        "Complaint ID": 2991112,
        "Submitted via": "Web",
        "Date submitted": 43326,
        "Date received": 43328,
        "State": "DC",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6862692,
        "Submitted via": "Web",
        "Date submitted": 45035,
        "Date received": 45035,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "No"
    },
    {
        "Complaint ID": 3093135,
        "Submitted via": "Web",
        "Date submitted": 43440,
        "Date received": 43440,
        "State": "FL",
        "Product": "Mortgage",
        "Sub-product": "Other type of mortgage",
        "Issue": "Struggling to pay mortgage",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6188850,
        "Submitted via": "Web",
        "Date submitted": 44875,
        "Date received": 44875,
        "State": "TX",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6239495,
        "Submitted via": "Referral",
        "Date submitted": 44887,
        "Date received": 44888,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3592843,
        "Submitted via": "Web",
        "Date submitted": 43925,
        "Date received": 43925,
        "State": "NY",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3076503,
        "Submitted via": "Web",
        "Date submitted": 43420,
        "Date received": 43424,
        "State": "TX",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Fees or interest",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5781200,
        "Submitted via": "Web",
        "Date submitted": 44760,
        "Date received": 44760,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6127521,
        "Submitted via": "Web",
        "Date submitted": 44859,
        "Date received": 44859,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5223129,
        "Submitted via": "Web",
        "Date submitted": 44607,
        "Date received": 44607,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "No"
    },
    {
        "Complaint ID": 6458454,
        "Submitted via": "Web",
        "Date submitted": 44945,
        "Date received": 44945,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "No"
    },
    {
        "Complaint ID": 5668489,
        "Submitted via": "Web",
        "Date submitted": 44726,
        "Date received": 44726,
        "State": "MI",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6068024,
        "Submitted via": "Web",
        "Date submitted": 44845,
        "Date received": 44845,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5724436,
        "Submitted via": "Phone",
        "Date submitted": 44742,
        "Date received": 44742,
        "State": "MD",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6189181,
        "Submitted via": "Web",
        "Date submitted": 44876,
        "Date received": 44876,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6064564,
        "Submitted via": "Web",
        "Date submitted": 44842,
        "Date received": 44842,
        "State": "MO",
        "Product": "Vehicle loan or lease",
        "Sub-product": "Loan",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "No"
    },
    {
        "Complaint ID": 4622571,
        "Submitted via": "Web",
        "Date submitted": 44419,
        "Date received": 44419,
        "State": "FL",
        "Product": "Debt collection",
        "Sub-product": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6034441,
        "Submitted via": "Web",
        "Date submitted": 44834,
        "Date received": 44834,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "Government benefit card",
        "Issue": "Problem with a purchase or transfer",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6579635,
        "Submitted via": "Web",
        "Date submitted": 44973,
        "Date received": 44973,
        "State": "NJ",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub-product": "Domestic (US) money transfer",
        "Issue": "Other transaction problem",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 7208864,
        "Submitted via": "Web",
        "Date submitted": 45112,
        "Date received": 45112,
        "State": "NY",
        "Product": "Vehicle loan or lease",
        "Sub-product": "Loan",
        "Issue": "Struggling to pay your loan",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6231510,
        "Submitted via": "Web",
        "Date submitted": 44888,
        "Date received": 44888,
        "State": "CA",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3669052,
        "Submitted via": "Web",
        "Date submitted": 43977,
        "Date received": 43977,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Problem with a credit reporting company's investigation into an existing problem",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3297104,
        "Submitted via": "Web",
        "Date submitted": 43651,
        "Date received": 43651,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 7209138,
        "Submitted via": "Web",
        "Date submitted": 45112,
        "Date received": 45112,
        "State": "ID",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Other features, terms, or problems",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 4291119,
        "Submitted via": "Referral",
        "Date submitted": 44294,
        "Date received": 44298,
        "State": "FL",
        "Product": "Mortgage",
        "Sub-product": "Conventional home mortgage",
        "Issue": "Trouble during payment process",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5146042,
        "Submitted via": "Web",
        "Date submitted": 44586,
        "Date received": 44586,
        "State": "NY",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3142516,
        "Submitted via": "Web",
        "Date submitted": 43500,
        "Date received": 43500,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5131244,
        "Submitted via": "Web",
        "Date submitted": 44581,
        "Date received": 44581,
        "State": "NY",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6022257,
        "Submitted via": "Web",
        "Date submitted": 44832,
        "Date received": 44832,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6026873,
        "Submitted via": "Web",
        "Date submitted": 44832,
        "Date received": 44832,
        "State": "FL",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit reporting",
        "Issue": "Incorrect information on your report",
        "Company response to consumer": "Closed with non-monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3297138,
        "Submitted via": "Web",
        "Date submitted": 43651,
        "Date received": 43651,
        "State": "TX",
        "Product": "Mortgage",
        "Sub-product": "FHA mortgage",
        "Issue": "Trouble during payment process",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5676146,
        "Submitted via": "Web",
        "Date submitted": 44727,
        "Date received": 44727,
        "State": "NY",
        "Product": "Money transfer, virtual currency, or money service",
        "Sub-product": "Domestic (US) money transfer",
        "Issue": "Other transaction problem",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6964251,
        "Submitted via": "Web",
        "Date submitted": 45057,
        "Date received": 45058,
        "State": "GA",
        "Product": "Mortgage",
        "Sub-product": "FHA mortgage",
        "Issue": "Trouble during payment process",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6964244,
        "Submitted via": "Web",
        "Date submitted": 45057,
        "Date received": 45058,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "Government benefit card",
        "Issue": "Problem with a purchase or transfer",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6234439,
        "Submitted via": "Web",
        "Date submitted": 44887,
        "Date received": 44887,
        "State": "MO",
        "Product": "Debt collection",
        "Sub-product": "Credit card debt",
        "Issue": "Took or threatened to take negative or legal action",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3255620,
        "Submitted via": "Web",
        "Date submitted": 43613,
        "Date received": 43613,
        "State": "MA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5675175,
        "Submitted via": "Phone",
        "Date submitted": 44727,
        "Date received": 44769,
        "State": "NY",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 5763246,
        "Submitted via": "Web",
        "Date submitted": 44755,
        "Date received": 44769,
        "State": "NC",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Other features, terms, or problems",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 3820159,
        "Submitted via": "Web",
        "Date submitted": 44071,
        "Date received": 44071,
        "State": "CA",
        "Product": "Credit card or prepaid card",
        "Sub-product": "Government benefit card",
        "Issue": "Trouble using the card",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6965959,
        "Submitted via": "Web",
        "Date submitted": 45057,
        "Date received": 45057,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Problem with a lender or other company charging your account",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 4185802,
        "Submitted via": "Web",
        "Date submitted": 44259,
        "Date received": 44259,
        "State": "CA",
        "Product": "Checking or savings account",
        "Sub-product": "Checking account",
        "Issue": "Managing an account",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 6190474,
        "Submitted via": "Web",
        "Date submitted": 44876,
        "Date received": 44876,
        "State": "NY",
        "Product": "Credit reporting, credit repair services, or other personal consumer reports",
        "Sub-product": "Credit repair services",
        "Issue": "Confusing or missing disclosures",
        "Company response to consumer": "Closed with explanation",
        "Timely response?": "Yes"
    },
    {
        "Complaint ID": 4276281,
        "Submitted via": "Referral",
        "Date submitted": 44290,
        "Date received": 44292,
        "State": "NC",
        "Product": "Credit card or prepaid card",
        "Sub-product": "General-purpose credit card or charge card",
        "Issue": "Problem with a purchase shown on your statement",
        "Company response to consumer": "Closed with monetary relief",
        "Timely response?": "Yes"
    }
]